# Generated by Django 4.2.7 on 2023-11-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("degree_checklist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="degree_program",
            field=models.ForeignKey(
                db_column="program_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="degree_checklist.degreeprogram",
            ),
        ),
    ]
