# Generated by Django 4.2.7 on 2023-11-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("degree_checklist", "0002_alter_course_degree_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="degree_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="degree_checklist.degreeprogram",
            ),
        ),
    ]
