# Generated by Django 4.2.7 on 2023-11-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("degree_checklist", "0006_alter_course_degree_program"),
    ]

    operations = [
        migrations.RenameField(
            model_name="includesdegreespecific",
            old_name="Degreespecific_requirement",
            new_name="degreespecific_requirement",
        ),
        migrations.RemoveField(model_name="has", name="Degreespecific_requirement",),
        migrations.AlterField(
            model_name="includes",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="includes",
                to="degree_checklist.course",
            ),
        ),
        migrations.AlterField(
            model_name="includesdegreespecific",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="includes_degreespecific",
                to="degree_checklist.course",
            ),
        ),
        migrations.AlterField(
            model_name="requires",
            name="core_requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requires",
                to="degree_checklist.corerequirement",
            ),
        ),
        migrations.AddField(
            model_name="has",
            name="degreespecific_requirement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has",
                to="degree_checklist.degreespecificrequirement",
            ),
            preserve_default=False,
        ),
    ]
