# Generated by Django 4.2.7 on 2023-11-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("degree_checklist", "0008_includes_degree_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="core_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="degree_checklist.corerequirement",
            ),
        ),
    ]
