# Generated by Django 4.2.7 on 2023-11-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("degree_checklist", "0011_alter_course_department"),
    ]

    operations = [
        migrations.RemoveField(model_name="includes", name="degree_program",),
    ]
