# Generated by Django 4.2.7 on 2023-11-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("degree_checklist", "0012_remove_includes_degree_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="includes",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="degree_checklist.course",
            ),
        ),
    ]
