# Generated by Django 4.2.7 on 2023-11-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("degree_checklist", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AccountingRequirement", new_name="DegreespecificRequirement",
        ),
        migrations.RenameModel(
            old_name="IncludesAccounting", new_name="IncludesDegreespecific",
        ),
        migrations.RenameField(
            model_name="degreespecificrequirement",
            old_name="AccountingReqID",
            new_name="DegreespecificReqID",
        ),
        migrations.RenameField(
            model_name="degreespecificrequirement",
            old_name="AccountingReqName",
            new_name="DegreespecificReqName",
        ),
        migrations.RenameField(
            model_name="has",
            old_name="accounting_requirement",
            new_name="Degreespecific_requirement",
        ),
        migrations.RenameField(
            model_name="includesdegreespecific",
            old_name="accounting_requirement",
            new_name="Degreespecific_requirement",
        ),
    ]
